.eslintrc.js, .prettierrc.js, App.tsx, __tests__/App-test.tsx, index.js, package-lock.json, package.json, src/components/BottomSheetContent.tsx, src/components/Complete.tsx, src/components/RoundedCount.tsx, src/components/SelectedTaskCover.tsx, src/components/Task.tsx, src/components/TaskMy.tsx, src/components/Week.tsx, src/screens/AddTask.tsx, src/screens/Home.tsx, src/screens/MyTask.tsx
=> fix: fix eslint and prettier

src/components/AddTaskItem.tsx, src/components/BottomSheet.tsx, src/components/CustomText.tsx, src/components/TaskListView.tsx, src/utils/font.ts
=> feature #32. Font Style 객체 적용

package.json, src/components/AddTaskItem.tsx, src/components/BottomSheet.tsx, src/components/CollapsibleToolbar.tsx, src/components/ScrollingButtonMenu.tsx, src/components/SelectCategoryWithTemplate.tsx, src/components/TemplateCard.tsx, src/models/Category.ts, src/models/Template.ts, src/models/TemplateTask.ts, src/screens/AddTask.tsx, src/screens/Login.tsx, src/screens/vm/addTaskVM.ts, yarn.lock
- collapsible toolbar 개선 필요
fix #22
=> feat #22. 테스크 생성 카테고리/템플릿 선택 뷰 개발

ios/Podfile.lock, ios/routine.xcodeproj/project.pbxproj, src/components/Calendar.tsx, yarn.lock
=> fix: OS에 따라 터치영역 높이 변경

App.tsx, package.json, src/apis/authAPI.tsx, src/components/AlarmSettingCard.tsx, src/navigations/MainNavigator.tsx, src/screens/Home.tsx, src/screens/Login.tsx, src/stores/AuthStore.ts, src/utils/api.ts, src/utils/swr.ts
=> 로그인 API 적용 및 api 유틸 기능 강화 #51 #68

src/components/Calendar.tsx, src/components/CollapsibleToolbar.tsx, src/components/FoldableSelector.tsx, src/components/Icon.tsx, src/components/TaskListItem.tsx, src/navigations/MainNavigator.tsx, src/screens/Home.tsx
=> fix: Icon Component 정리

src/apis/authAPI.tsx, src/components/TaskDetailPopup.tsx, src/screens/Home.tsx, src/stores/AuthStore.ts, src/utils/swr.ts
=> feat: profile api 연동

src/apis/templateAPI.tsx, src/components/ScrollingButtonMenu.tsx, src/models/Template.ts, src/navigations/MainNavigator.tsx, src/navigations/types.ts, src/screens/TaskList.tsx, src/screens/TemplateList.tsx, src/utils/swr.ts
=> feat: 카테고리 api 연동

package.json, src/screens/EditTask.tsx, src/utils/showToast.ts, yarn.lock
- `react-native-root-toast` 라이브러리 사용했습니다.
- 컴포넌트로 만들면 디자인은 정확히 반영되지만, 사용하는 부분마다 컴포넌트를 반영해줘야해서 일단은 함수 호출로 구현했습니다. 기본 디자인이라 괜찮을 것 같아요!
=> feat:  `toast` 메시지 기능 추가

src/apis/routinAPI.tsx, src/components/AddTaskItem.tsx, src/components/AlarmSettingCard.tsx, src/components/CustomTextInput.tsx, src/components/TemplateCard.tsx, src/components/TimeSettingCard.tsx, src/components/TimeSettingContainer.tsx, src/components/WheelPicker.tsx, src/models/RoutineCreateRq.ts, src/models/RoutineCreateRs.ts, src/models/TemplateTask.ts, src/navigations/MainNavigator.tsx, src/navigations/types.ts, src/screens/EditTask.tsx, src/screens/TaskList.tsx, src/screens/vm/editTaskVM.ts, src/stores/EditTaskStore.ts
- 커스텀 테스크 추가 가능하게 변경
- task add api 연결
- wheel picker 이벤트 종류 후에 선택되게 개선
- 시간 선택 로직 추가
- 알람 설정 On/off 로직 추가
=> task add api 연결 및 로직 개선

src/components/CustomText.tsx, src/components/CustomTextInput.tsx, src/components/DailyLoopCard.tsx, src/components/FoldableContainer.tsx, src/components/FoldableSelector.tsx, src/components/TimeSettingContainer.tsx, src/components/WeekLoopCard.tsx, src/components/WheelPicker.tsx, src/screens/EditTask.tsx
- 드롭다운 펼쳐졌을 때 아래 요소들이 버튼에 가리는 (잘려서 보여지는) 현상이 발생함.
- 알람 설정은 아직 on/off 로만 구분되기 때문에 `selected` 요소 노출을 할 수 없음.
=> `EditTask` UI 디벨롭

ios/Podfile.lock, ios/routine.xcodeproj/project.pbxproj, src/components/Calendar.tsx, src/components/TaskListView.tsx, src/components/WheelPicker.tsx, src/screens/Home.tsx, src/stores/CalendarStore.ts
=> fix: Home 변경된 UI 반영

src/components/AlarmSettingCard.tsx, src/components/CustomModal.tsx, src/components/FriendBox.tsx, src/components/FriendInviteCard.tsx, src/components/TimeSettingCard.tsx, src/components/UserProfileImage.tsx, src/models/Friend.ts, src/screens/EditTask.tsx
=> 파티원 초대 UI 추가 작업

src/apis/routinAPI.tsx, src/components/TaskDetailPopup.tsx, src/navigations/types.ts, src/screens/EditTask.tsx, src/stores/EditTaskStore.ts
- 태스크 수정 API 연결 확인
- 태스크 삭제 API 연결 확인
- 홈에서 태스크 삭제 API 연결
fix #72
=> 태스크 수정/삭제 API 연결 버그 수정

src/apis/routinAPI.tsx, src/components/CollapsibleToolbar.tsx, src/components/CustomText.tsx, src/models/Template.ts, src/screens/TaskList.tsx
fix. #93 
fix. #95 
fix. #89 
- description api 연결
- 애니메이션 개선
- 전체 담기 API 연결
=> 테스크 리스트 헤더에 미작업 된 api 연결 및 애니메이션 개선

ios/routine.xcodeproj/project.pbxproj, src/components/AlarmSettingCard.tsx, src/components/CollapsibleCard.tsx, src/components/DailyLoopCard.tsx, src/components/EditTaskView.tsx, src/components/FoldableContainer.tsx, src/components/FriendBox.tsx, src/components/FriendInviteCard.tsx, src/components/Header.tsx, src/components/Icon.tsx, src/components/InviteButton.tsx, src/components/InviteMessageView.tsx, src/components/TimeSettingCard.tsx, src/components/WeekLoopCard.tsx, src/models/Friend.ts, src/navigations/MainNavigator.tsx, src/navigations/types.ts, src/screens/EditTask.tsx, src/screens/InviteAccept.tsx, src/screens/InviteDetail.tsx, src/screens/InviteIntro.tsx
- 로띠, 로딩 적용 필요함.
- 임시 데이터 `task` 없애고, 링크 통해서 실제 데이터 받아오는 작업 필요함.
=> 친구 초대 받는 플로우 UI 구현

src/components/CustomModal.tsx, src/screens/Home.tsx
- 아직 주 단위 테스크 완료 시의 팝업 표시는 적용하지 못했습니다. 이 부분은 주 단위 테스크 퍼센트 표시와 같이 작업하면 좋을 것 같습니다.
=> 테스크 완전히 완료했을 때 팝업 표시

src/components/Calendar.tsx, src/components/WheelPicker.tsx
- 선택 정확도를 높이기 위해 `onScrollEndDrag` 대신 `onMomentumScrollEnd` 로 변경했습니다.
=> fix: 월별 모달 현재 날짜 키우기

src/components/EditTaskView.tsx, src/components/InviteButton.tsx, src/components/TaskListView.tsx, src/screens/EditTask.tsx
=> fix: 상단, 하단 그라데이션 추가

src/apis/routinAPI.tsx, src/navigations/types.ts, src/screens/InviteAccept.tsx, src/screens/InviteIntro.tsx
=> 친구초대 api 연동

src/components/EditTaskView.tsx
=> 하루동안과 시간설정 싱크 맞지 않던 현상 수정

src/apis/routinAPI.tsx, src/components/EditTaskView.tsx, src/components/FriendBox.tsx, src/components/FriendInviteCard.tsx, src/components/UserProfileImage.tsx, src/models/Friend.ts, src/models/RoutineTaskUnit.ts, src/navigations/MainNavigator.tsx, src/screens/EditTask.tsx, src/screens/InviteAccept.tsx, src/screens/InviteDetail.tsx, src/stores/EditTaskStore.ts
=> feat #151. 테스크와 친구 초대장에 친구 리스트 추가

src/screens/Home.tsx
=> feat: 주차별 테스크 완료 퍼센트 반영 & 주 테스크 완료 시 팝업 표시

src/components/TaskListItem.tsx, src/components/TaskListView.tsx, src/models/Task.ts, src/stores/AuthStore.ts
단, 서버측에서 예상과 달리 아직 만들어지지 않은 유닛에 친구 부분이 없어서 확인 필요 !
=> 친구 공유까지 반영된 퍼센트 계산
